# Generated by Django 4.1.5 on 2023-01-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rate',
            new_name='Rate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
    ]
