# Generated by Django 4.1.5 on 2023-01-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_price_post_cost_rename_date_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
    ]
