# Generated by Django 4.1.5 on 2023-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_image_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
