# Generated by Django 4.1.5 on 2023-01-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_image_image_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
