# Generated by Django 4.1.5 on 2023-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_delete_image_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
