# Generated by Django 4.1.5 on 2023-01-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_image_alter_post_options_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
