# Generated by Django 4.1.4 on 2023-01-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
